FROM gradle:7.6-jdk17 AS build

WORKDIR /api

COPY api/build.gradle api/settings.gradle ./
COPY api/src ./src

RUN gradle build

FROM openjdk:17-slim

WORKDIR /api

COPY --from=build /api/build/libs/taskmaster.jar .

CMD ["java", "-jar", "taskmaster.jar"]